name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # For example, we could limit to path changes inside docs-site
    # paths:
    #   - 'docs-site/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs-site/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: docs-site

      - name: Build Docusaurus
        run: npm run build
        working-directory: docs-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/build
          publish_branch: gh-pages
